namespace MyApp.Models
{
    // The following model was adapted from poe ai
    // Link: https://poe.com/
    public class EventOrAnnouncement
    {
        public string Title { get; set; } = null!;

        public string Description { get; set; } = null!;

        public EventOrAnnouncementType Type { get; set; }

        public string CreatedBy { get; set; } = "User";

        public DateOnly CreatedAt { get; set; } = DateOnly.FromDateTime(DateTime.Today);


        public EventCategory? Category { get; set; } = null!;
        public string? Organiser { get; set; } = null;
        public string? Location { get; set; } = null;
        public DateOnly? Date { get; set; } = null;
        public TimeOnly? StartTime { get; set; } = null;
        public TimeOnly? EndTime { get; set; } = null;

    }


    public enum EventOrAnnouncementType
    {
        Event,
        Announcement
    }

    // The following categories were generated by Poe AI
    // Link: https://poe.com
    public enum EventCategory
    {
        Conference,
        Workshop,
        Webinar,
        Social,
        Sports,
        Cultural,
        Community,
        Corporate,
        Educational,
        Religious,
        Music,
        Food_and_Drink,
        Health_and_Wellness,
        Tech,
        Environmental
    }
}
