using Microsoft.AspNetCore.Components.Forms;
using System.ComponentModel.DataAnnotations;

namespace MyApp.Models
{
    public class Issue
    {
        [Required(ErrorMessage = "A Location Must Be Provided")]
        [StringLength(255, MinimumLength = 1, ErrorMessage = "Length of Location needs to be between 1 and 255")]
        public string Location { get; set; }


        [Required(ErrorMessage = "A Category Must Be Selected")]
        public string Category { get; set; }


        [Required(ErrorMessage = "A Description Must Be Provided")]
        [StringLength(255, MinimumLength = 1, ErrorMessage = "Length of Description needs to be between 1 and 255")]
        public string Description { get; set; }


        public IBrowserFile[]? MediaAttachments { get; set; } = new IBrowserFile[2];
    }




    public static class IssueCategories
    {
        // The following categories were generated by ChatGPT
        // Author: OpenAI
        // Link: https://poe.com/chat/3krtaumsxr1yxb48tx2
        // Prompt: what are the different categories of municipality issues

        public static string[] Array = {
            "Infrastructure And Utilities",
            "Public Safety",
            "Land Use And Zoning",
            "Health And Social",
            "Economic Development",
            "Education And Culture",
            "Finance And Administration"
        };

        public enum Enum
        {
            Infrastructure_And_Utilities,
            Public_Safety,
            Land_Use_And_Zoning,
            Health_And_Social,
            Economic_Development,
            Education_And_Culture,
            Finance_And_Administration
        }

        // Attempted to store badge colors in dictionary however it wasn't working for some reason.
        //public static Dictionary<string, string> ClassColors = new()
        //{
        //    { "Infrastructure And Utilities", " text-violet-700 border-violet-500 " },
        //    { "Public Safety", "text-yellow-700 border-yellow-500" },
        //    { "Land Use And Zoning", "text-lime-700 border-lime-500" },
        //    { "Health And Social", "text-green-700 border-green-500" },
        //    { "Economic Development", "text-cyan-700 border-cyan-500" },
        //    { "Education And Culture", "text-orange-700 border-orange-500" },
        //    { "Finance And Administration", "text-emerald-700 border-emerald-500" }
        //};
    }


}
