using Microsoft.AspNetCore.Components.Forms;
using System.ComponentModel.DataAnnotations;

namespace MyApp.Models
{
    public class Issue
    {
        [Required(ErrorMessage = "A Location Must Be Provided")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Length of Location needs to be between 1 and 255")]
        public string Location { get; set; }


        [Required(ErrorMessage = "A Category Must Be Selected")]
        public string Category { get; set; }


        [Required(ErrorMessage = "A Description Must Be Provided")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Length of Description needs to be between 1 and 255")]
        public string Description { get; set; }


        public IBrowserFile[]? MediaAttachments { get; set; } = new IBrowserFile[2];
    }




    public static class IssueCategories
    {
        // The following categories were generated by ChatGPT
        // Author: OpenAI
        // Link: https://poe.com/chat/3krtaumsxr1yxb48tx2
        // Prompt: what are the different categories of municipality issues

        public static string[] Array = {
            "Infrastructure And Utilities",
            "Public Safety",
            "Land Use And Zoning",
            "Health And Social",
            "Economic Development",
            "Education And Culture",
            "Finance And Administration"
        };

        public enum Enum
        {
            Infrastructure_And_Utilities,
            Public_Safety,
            Land_Use_And_Zoning,
            Health_And_Social,
            Economic_Development,
            Education_And_Culture,
            Finance_And_Administration
        }
    }


}
